app/views/players/links.html.haml
260 wanted his youtube added :)
Sorry about last time, I checked how everything looked this time!
=> [links] Added Ironman260's yt

app/models/player.rb, db/migrate/20191017031022_add_hcim_has_died_to_players.rb, db/schema.rb
Register HCIM's death with timestamp and boolean when player account type changes from HCIM to IM.
This is only a database addition for now, but I imagine this being a nifty feature in the future.
=> [DATA] Register HCIM's death

app/assets/stylesheets/players.scss.erb, app/views/players/_header.html.haml, app/views/players/calcs.html.haml, app/views/players/changelog.html.haml, app/views/players/combat.html.haml, app/views/players/compare.html.haml, app/views/players/controls.html.haml, app/views/players/donate.html.haml, app/views/players/dps.html.haml, app/views/players/ehp.html.haml, app/views/players/fake.html.haml, app/views/players/index.html.haml, app/views/players/links.html.haml, app/views/players/oldchangelog.html.haml, app/views/players/possible_fakes.html.haml, app/views/players/ranks.html.haml, app/views/players/records.html.haml, app/views/players/show.html.haml, app/views/players/tracking.html.haml
A small change set to remove some code that was duplicated in the header between different views.
=> [FRNT] create reusable template for header links

app/views/players/index.html.haml
=> Add news about f2p team rumble comp

app/views/players/changelog.html.haml
[update post](https://secure.runescape.com/m=news/poll-69-bh-rewards-and-welcome-screen?oldschool=1)
=> Add new explore emote update text in changelog

app/views/players/show.html.haml
=> Add templeosrs link on profile page

app/controllers/players_controller.rb
Should fix #53 if I understand correctly
GIF of how it works
[https://gyazo.com/a0e215f8c030157e169073fb035fcca5](https://gyazo.com/a0e215f8c030157e169073fb035fcca5)
=> Don't update player if updated less than a minute ago

app/views/players/_supporters.html.haml
=> Add recent donations panel

app/services/hiscores.rb
=> [FIX] fix table_url to clean player name before generating URL

.gitignore, app/controllers/admin_controller.rb, app/views/admin/index.html.haml, config/application.rb, config/local_env.yml.example, config/routes.rb
Very, very basic admin page (f2p.wiki/admin)
Still will need to update `player.rb` for adding in supporters
Default user and pass is admin admin, but I will set the user and pass on heroku when merged
=> Admin page

app/views/players/links.html.haml
Feels like the guide should be in the guides section, despite being a spreadsheet
=> Move F2P Music Guide to Guides section

app/controllers/players_controller.rb, app/views/players/ranks.html.haml, app/views/players/records.html.haml, app/views/players/tracking.html.haml
Fixes #80 
Still not great, as with the previous restriction checkboxes they don't carry through the session until reset for some reason
[https://i.gyazo.com/e73895197f285bdc1fb8c4cc689322de.mp4](https://i.gyazo.com/e73895197f285bdc1fb8c4cc689322de.mp4)
=> Remove lvl 3 cb's from 10 hp filter

app/assets/stylesheets/players.scss.erb, app/views/players/index.html.haml, app/views/players/ranks.html.haml, app/views/players/records.html.haml, app/views/players/show.html.haml, app/views/players/tracking.html.haml
I think this will really help the #91 issue which I am getting in-game even more frequently now.
I also added placeholders to the search and compare forms on all pages as it looked somewhat strange to me for us to only have a placeholder on one form.
Edit: Forgot to mention I did test and the forms worked perfectly from the front page.
=> Add Search and Add to Hiscores Forms to Frontpage

app/views/players/changelog.html.haml, app/views/players/donate.html.haml, app/views/players/ehp.html.haml, app/views/players/faqs.html.haml, app/views/players/index.html.haml, app/views/players/links.html.haml, app/views/players/show.html.haml
There's the rel="noopener noreferrer" vulnerability is a good one to stay ahead up. Plus I think from a web ux standpoint external links are expected to open in new tabs.
Can read more about the vulnerability here - [https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/)
=> Add target='_blank' and rel='noopener noreferrer' to all external links

app/models/player.rb
Addresses #49 
Did some testing by doing the following:
* rake db:seed (stats are very old, so xp gains should be guaranteed for most players)
* manually set a player's `updated_at` in rails console `Player.find_player("UncleTomas").update_attributes(:last_updated => "2019-12-02 00:00:00")`
* update player
* make sure that the expected gains were not associated with the incorrect time period
* case 1: over 1 year out of date --> 0 gains for day/week/month/year
* case 2: over 1 month out of date --> 0 gains for day/week/month, some gains for year
* case 3: over 1 week out of date --> 0 gains for day/week, some gains for month/year
* case 4: over 1 day out of date --> 0 gains for day, some gains for week/month/year
* case 5: less than 1 day out of date --> some gains for day/week/month/year …
=> Fix gains time period

app/controllers/clans_controller.rb
=> [FIX] Also include a fix to clans non-combat ranking.

app/assets/javascripts/combat-dps.js, app/views/players/dps.html.haml
=> Calcs golems

app/controllers/clans_controller.rb, app/controllers/players_controller.rb, app/views/clans/show.html.haml, app/views/players/ranks.html.haml, app/views/players/show.html.haml
Commented out in case we need to easily retrieve it in the future
#108
=> Remove frontend displays of All Clues as it is confusing

UPDATING_EHP.md, app/views/players/changelog.html.haml, config/initializers/assets.rb
Using Terrathrone/Autumn Elergy's spreadsheet (https://docs.google.com/spreadsheets/d/1awoU-SaSmorJgA7YhV-LaJpu_M5gVkSfg8SyffIBhxI/edit#gid=28583017), all radical changes have already been polled, so I used this spreadsheet to do some very minor updates.
=> Minor ehp changes 2023 02 02

db/migrate/20231120080237_update_xp_start_to_big_int.rb, db/schema.rb
`heroku run bundle exec rake db:migrate`
If it works, Netbook Pro should be able to be updated
=> Fix Netbook pro bugging out int4 xp columns
